# Generated by Django 3.1.4 on 2020-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('cp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_llegada', models.DateField(auto_now_add=True)),
                ('palets', models.IntegerField()),
            ],
        ),
    ]
