# Generated by Django 3.1.4 on 2020-12-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logica.cliente')),
            ],
        ),
    ]
