# Generated by Django 3.1.4 on 2020-12-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='exportado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.cliente'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVenta', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.lote')),
            ],
        ),
    ]
