# Generated by Django 3.1.4 on 2020-12-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_auto_20201207_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='exportado',
            field=models.BooleanField(default=False),
        ),
    ]
