# Generated by Django 3.1.4 on 2020-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_auto_20201207_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ventas',
            field=models.ManyToManyField(blank=True, null=True, to='logica.Venta'),
        ),
    ]
